#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_FILE_PATH_LENGTH 512
#define MAX_LINE_WIDTH 1024
#define SPACE_DELIMITER " "
#define FORWARD_SLASH_DELIMITER "/"
#define INDEX_UNDEFINED (-1)

#endif // CONSTANTS_H
